- name: StorageGRID administration playbook
  hosts: localhost
  gather_facts: false

  vars:
    storagegrid_api_url: "https://192.168.4.230:443"
    auth_token: "e4162885-6bda-4924-945c-af1e6cc602c5"  # replace with your actual token

  tasks:
    - name: Create or update a StorageGRID tenant account
      netapp.storagegrid.na_sg_grid_account:
        api_url: "{{ storagegrid_api_url }}"
        auth_token: "{{ auth_token }}"
        validate_certs: false
        state: present
        name: "example-tenant"
        protocol: s3
        management: true
          #allow_compliance_mode: false
          # max_retention_days: 365
        use_own_identity_source: false
        allow_platform_services: false
        password: "br@@mspun111"
        quota_size: 10240

    - name: Create an S3 bucket within the tenant
      netapp.storagegrid.na_sg_org_bucket:
        api_url: "{{ storagegrid_api_url }}"
        auth_token: "{{ auth_token }}"
        validate_certs: false
        state: present
        name: "ansiblebucket1"
          #tenant: "example-tenant"
        bucket_versioning_enabled: true
        s3_object_lock_enabled: false
        capacity_limit: 10000

