---

- name: first play
  hosts: all
  become: true
  tasks:

  - name: install apache
    yum:
      name: httpd
      state: present 

- name: second play
  hosts: all
  tasks:

  - name: install ksh
    yum:
      name: ksh
      state: present 

