---
- name: List StorageGRID tenants
  hosts: localhost
  gather_facts: false
  vars:
    admin_node_ip: "192.168.4.230"
    bearer_token: "e4162885-6bda-4924-945c-af1e6cc602c5"

  tasks:
    - name: Get list of tenants from StorageGRID
      uri:
        url: "https://{{ admin_node_ip }}/api/v3/grid/accounts"
        method: GET
        headers:
          Authorization: "Bearer {{ bearer_token }}"
          Accept: "application/json"
        validate_certs: false
      register: tenant_response

    - name: Display tenants JSON
      debug:
        var: tenant_response.json


